on:
  push:
    tags:
      - 'linux_surface-*'

env:
  GPG_KEY_ID: 0F10857DF3688E72

jobs:
  build:
    name: Build Linux kernel package
    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        # Install makepkg deps
        pacman --noconfirm -Syu
        pacman --noconfirm -S sudo binutils fakeroot base-devel git   \
                              xmlto docbook-xsl kmod inetutils bc dtc \
                              aarch64-linux-gnu-gcc aarch64-linux-gnu-glibc

        # Fix permissions (can't makepkg as root)
        echo "nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers

    - name: Set up makepkg-aarch64 for cross-compilation
      run: |
        cd makepkg-aarch64

        # Fix permissions (can't makepkg as root)
        chown -R nobody .

        # Build and install 
        su nobody --pty -p -s /bin/bash -c 'makepkg -fi --syncdeps --skippgpcheck --noconfirm'

    - name: Build Package
      run: |
        cd linux-raphael

        # Fix permissions (can't makepkg as root)
        chown -R nobody .

        # Package compression settings (Matches latest Arch)
        export PKGEXT='.pkg.tar.zst'
        export COMPRESSZST=(zstd -c -T0 --ultra -20 -)
        export MAKEFLAGS="-j2"

        # Build
        su nobody --pty -p -s /bin/bash -c 'makepkg-aarch64 -f --syncdeps --skippgpcheck --noconfirm'

    - name: Prepare release
      run: |
        mkdir release
        mv linux-raphael/*.pkg.tar.zst release

    - name: Sign packages
      env:
        GPG_KEY: ${{ secrets.LINUX_RAPHAEL_GPG_KEY }}
      run: |
        cd release

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
        export GPG_TTY=$(tty)

        # sign packages
        ls *.pkg.tar.zst | xargs -L1 gpg --detach-sign --batch --no-tty -u $GPG_KEY_ID

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-raphael-aarch64-latest
        path: release
